-- MySQL Script generated by MySQL Workbench
-- Thu Apr 30 22:37:19 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema medicitas
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `medicitas` ;

-- -----------------------------------------------------
-- Schema medicitas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `medicitas` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
SHOW WARNINGS;
USE `medicitas` ;

-- -----------------------------------------------------
-- Table `citas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `citas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `citas` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `paciente_id` BIGINT UNSIGNED NOT NULL,
  `medico_id` BIGINT UNSIGNED NOT NULL,
  `fecha_hora` DATETIME NOT NULL,
  `estado` ENUM('pendiente_pago', 'pagada', 'confirmada', 'cancelada', 'completada') NULL DEFAULT 'pendiente_pago',
  `motivo` TEXT NULL DEFAULT NULL,
  `monto` DECIMAL(10,2) NULL DEFAULT '150.00',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `encuestas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `encuestas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `encuestas` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cita_id` BIGINT UNSIGNED NOT NULL,
  `puntuacion` TINYINT NULL DEFAULT NULL,
  `comentario` TEXT NULL DEFAULT NULL,
  `respondida` TINYINT(1) NULL DEFAULT '0',
  `token` VARCHAR(64) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `token` ON `encuestas` (`token` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `especialidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `especialidades` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `especialidades` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `nombre` ON `especialidades` (`nombre` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `historial_clinico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `historial_clinico` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `historial_clinico` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `paciente_id` BIGINT UNSIGNED NOT NULL,
  `medico_id` BIGINT UNSIGNED NOT NULL,
  `cita_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `fecha` DATE NOT NULL,
  `diagnostico` TEXT NULL DEFAULT NULL,
  `tratamiento` TEXT NULL DEFAULT NULL,
  `receta` TEXT NULL DEFAULT NULL,
  `archivo_adjunto` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `medicos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `medicos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `medicos` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `especialidad_id` BIGINT UNSIGNED NOT NULL,
  `cmp` VARCHAR(20) NOT NULL,
  `telefono` VARCHAR(15) NULL DEFAULT NULL,
  `horario_atencion` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `cmp` ON `medicos` (`cmp` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pacientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pacientes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pacientes` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `dni` VARCHAR(8) NOT NULL,
  `telefono` VARCHAR(15) NULL DEFAULT NULL,
  `direccion` TEXT NULL DEFAULT NULL,
  `fecha_nacimiento` DATE NULL DEFAULT NULL,
  `seguro` VARCHAR(50) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `dni` ON `pacientes` (`dni` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pagos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pagos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pagos` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cita_id` BIGINT UNSIGNED NOT NULL,
  `monto` DECIMAL(10,2) NOT NULL,
  `metodo_pago` ENUM('tarjeta', 'yape', 'plin', 'transferencia') NULL DEFAULT 'tarjeta',
  `transaccion_id` VARCHAR(100) NULL DEFAULT NULL,
  `estado_pago` ENUM('pendiente', 'completado', 'fallido', 'reembolsado') NULL DEFAULT 'pendiente',
  `fecha_pago` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
